### ISSUE TITLE
There is a problem with the color of the table

### ISSUE THREAD

**Issue by tawoli** [oomusou/typora-github-dark#1]
Even lines of text are unclear

**Comment by tawoli** [comment]
表格偶数行的颜色导致了输出字体显示不清楚
![image](https://user-images.githubusercontent.com/19144439/87379895-dfaa5c80-c5c3-11ea-9a73-efd81522d94c.png)

**Comment by oomusou** [comment]
我修正了這個問題，請更新到最新版
